-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 5da199bb8d60f764c0f77a20b0a1dc3a7640bcdd
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
        language_version: python3.5
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: autopep8-wrapper
        language_version: python3.5
        exclude: migrations\/[^/]*\.py
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: c25201a00e6b0514370501050cf2a8538ac12270
    hooks:
    -   id: forbid-crlf
        exclude: \.csv$
    -   id: forbid-tabs
        exclude: Makefile|\.bat$
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: 1.0.4
    hooks:
    -   id: python-import-sorter
        language_version: python3.5
        exclude: migrations\/[^/]*\.py
-   repo: git://github.com/guykisel/prospector-mirror
    sha: 00fbd80101566b1b9c873c71f2ab7b95b8bd0a7d
    hooks:
    -   id: prospector
        exclude: migrations\/[^/]*\.py
        args: ['-A', '--uses', 'django']
