repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.4
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
        language_version: python3.5
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: autopep8-wrapper
        language_version: python3.5
        exclude: migrations\/[^/]*\.py
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.4
    hooks:
    -   id: forbid-crlf
        exclude: \.csv$
    -   id: forbid-tabs
        exclude: Makefile|\.bat$
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: b57843b0b874df1d16eb0bef00b868792cb245c2
    hooks:
    -   id: python-import-sorter
        language_version: python3.5
        exclude: migrations\/[^/]*\.py
-   repo: local
    hooks:
    -   id: prospector
        name: Prospector
        description: 'This hook runs Prospector: https://github.com/landscapeio/prospector'
        entry: prospector
        language: system
        files: \.py$
        exclude: migrations\/[^/]*\.py$|settings\/[^/]*\.py$|^docs/conf\.py$
-   repo: https://github.com/prettier/prettier
    sha: 1.7.0
    hooks:
    -   id: prettier
        types: [file]
        files: \.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx)$
        exclude: \.min\.(js|css)$
